import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../components/Header';
import Banner from '../components/Banner'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>AirBnB-ME</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     
      {/* Header */}
      <Header/>
      {/* Banner */}
      <Banner/>
      <main className='max-w-7xl mx-auto px-8 sm:px-16'>
        <section className='pt-6'>
          <h2 className='font-semibold pb-6  text-4xl '>Explore nearby</h2>
          {/* Sever side rendering .. static rendering */}
        </section>
      </main>
     
    </div>
  )
};

export async function getStaticProps(){

};
